// layout.js (or a similar file for server-side logic)
import React from 'react';
import './globals.css'; // Import global styles
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Project Management System",
  description: "Generated by janvi jindal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      
        {children}
        <ToastContainer position="top-right" autoClose={5000} hideProgressBar />
      </body>
    </html>
  );
}
